const myVar = 'newText'
const dupa = 'dupa'
console.log('some text')
console.log('some blabla')
console.log('some whoa')
console.log('some and')
console.log('some else')
console.log(myVar)
console.log(dupa)
console.log(dupa)
console.log(dupa)
console.log(dupa)
console.log(dupa)
console.log(dupa)
console.log('huj dupa i kamieni kupa')
console.log('huj dupa i kamieni kupa')